name: 🐛 Bug report
about: Create a report to help us improve
title: '[Bug]: <title>'
labels:
  - bug
assignees: '0x219'
body:
  - type: markdown
    attributes:
      value: |
        🥳 **Thank you for contributing!**
