name: "🐛 Bug report"
description: Create a report to help us improve
title: '[Bug]: <title>'
labels:
  - bug
assignees: '0x219'
body:
  - type: markdown
    attributes:
      value: |
        🥳 **Thank you for contributing!**
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: 💭 Please enter...
    validations:
      required: true
